# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 220)
        self.title = QtWidgets.QLineEdit(Form)
        self.title.setGeometry(QtCore.QRect(120, 10, 271, 20))
        self.title.setObjectName("title")
        self.roastingLevel = QtWidgets.QLineEdit(Form)
        self.roastingLevel.setGeometry(QtCore.QRect(120, 40, 271, 20))
        self.roastingLevel.setObjectName("roastingLevel")
        self.ground = QtWidgets.QLineEdit(Form)
        self.ground.setGeometry(QtCore.QRect(120, 70, 271, 20))
        self.ground.setObjectName("ground")
        self.tasteDescription = QtWidgets.QLineEdit(Form)
        self.tasteDescription.setGeometry(QtCore.QRect(120, 100, 271, 20))
        self.tasteDescription.setObjectName("tasteDescription")
        self.price = QtWidgets.QLineEdit(Form)
        self.price.setGeometry(QtCore.QRect(120, 130, 271, 20))
        self.price.setObjectName("price")
        self.volume = QtWidgets.QLineEdit(Form)
        self.volume.setGeometry(QtCore.QRect(120, 160, 271, 21))
        self.volume.setObjectName("volume")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 101, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 101, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 101, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 101, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 101, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 101, 20))
        self.label_6.setObjectName("label_6")
        self.doneButton = QtWidgets.QPushButton(Form)
        self.doneButton.setGeometry(QtCore.QRect(10, 190, 381, 23))
        self.doneButton.setObjectName("doneButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Добавить элемент"))
        self.label.setText(_translate("Form", "Название"))
        self.label_2.setText(_translate("Form", "Степень обжарки"))
        self.label_3.setText(_translate("Form", "Молотый или нет"))
        self.label_4.setText(_translate("Form", "Описание вкуса"))
        self.label_5.setText(_translate("Form", "Цена"))
        self.label_6.setText(_translate("Form", "Объём"))
        self.doneButton.setText(_translate("Form", "Добавить"))
